#!/usr/bin/env Rscript
# generate_excel.R
# OUTPUT: Master Excel with Raw Counts, Unfiltered DE, AND Pathway Results

suppressPackageStartupMessages({
    library(openxlsx)
    library(dplyr)
    library(data.table)
    library(EnsDb.Hsapiens.v86)
    library(stringr)
})

# ==============================================================================
# SETUP
# ==============================================================================
args <- commandArgs(trailingOnly=TRUE)
if(length(args) < 4) stop("Usage: generate_excel.R <counts_file> <results_dir> <viz_dir> <output_file>")

counts_file <- args[1]
results_dir <- args[2]
viz_dir     <- args[3]  # NEW: Directory containing GSEA CSVs
outfile     <- args[4]

# Utility: Map Symbols
map_genes <- function(gene_ids) {
    clean_ids <- sub("\\..*", "", gene_ids)
    symbols <- mapIds(EnsDb.Hsapiens.v86, keys=clean_ids, column="SYMBOL", keytype="GENEID", multiVals="first")
    ifelse(is.na(symbols), clean_ids, symbols)
}

# Utility: Shorten Tab Names (Excel Limit = 31 chars)
make_tab_name <- function(filename) {
    # Remove prefix/suffix
    clean <- gsub("Analysis_", "", filename)
    clean <- gsub(".csv", "", clean)
    
    # Extract Contrast (first 2 words usually)
    parts <- str_split(clean, "_")[[1]]
    
    # Custom shortening for your specific project names
    contrast_map <- c(
        "therapy_impact" = "Therapy",
        "brain_adaptation" = "Brain",
        "total_evolution" = "Total",
        "core_brain_adaptation" = "Core"
    )
    
    # Identify Contrast
    contrast_key <- names(contrast_map)[sapply(names(contrast_map), function(x) grepl(x, clean))]
    short_contrast <- if(length(contrast_key)>0) contrast_map[contrast_key[1]] else parts[1]
    
    # Identify Database
    db_map <- c(
        "hallmark" = "Hallmark",
        "kegg" = "KEGG",
        "gobp" = "GO_BP",
        "reactome" = "Reactome",
        "dsigdb" = "Drugs",
        "brain_gmt" = "BrainGMT",
        "c2" = "C2"
    )
    
    db_key <- names(db_map)[sapply(names(db_map), function(x) grepl(x, clean))]
    short_db <- if(length(db_key)>0) db_map[db_key[1]] else "Pathways"
    
    # Combine (e.g., "Therapy_Hallmark")
    final_name <- paste0(short_contrast, "_", short_db)
    return(substr(final_name, 1, 31))
}

wb <- createWorkbook()

# ==============================================================================
# TAB 1: RAW COUNTS
# ==============================================================================
cat("LOG: Processing Raw Counts...\n")
if(file.exists(counts_file)) {
    counts_df <- read.table(counts_file, header=TRUE, row.names=1, check.names=FALSE)
    counts_df$Symbol <- map_genes(rownames(counts_df))
    counts_df <- counts_df %>% dplyr::select(Symbol, everything())
    addWorksheet(wb, "Raw_Read_Counts")
    writeData(wb, "Raw_Read_Counts", counts_df, rowNames=TRUE)
}

# ==============================================================================
# TABS 2+: DIFFERENTIAL EXPRESSION (UNFILTERED)
# ==============================================================================
contrasts <- list.files(file.path(results_dir, "tables/differential"), pattern=".results.tsv", full.names=TRUE)

for(f in contrasts) {
    cid <- sub(".deseq2.results.tsv", "", basename(f))
    sheet_name <- paste0("DE_", substr(cid, 1, 28)) # Prefix DE_ to distinguish
    
    cat(paste0("LOG: Adding DE Tab: ", sheet_name, "\n"))
    
    res_df <- read.table(f, header=TRUE, sep="\t", quote="")
    if (grepl("^[0-9]+$", rownames(res_df)[1])) rownames(res_df) <- res_df$gene_id
    if(!"symbol" %in% colnames(res_df)) res_df$symbol <- map_genes(rownames(res_df))
    
    first_cols <- c("symbol", "log2FoldChange", "pvalue", "padj")
    other_cols <- setdiff(colnames(res_df), first_cols)
    res_df <- res_df %>% dplyr::select(all_of(first_cols), all_of(other_cols))
    
    addWorksheet(wb, sheet_name)
    writeData(wb, sheet_name, res_df, rowNames=TRUE)
}

# ==============================================================================
# TABS 3+: PATHWAY ANALYSIS (GSEA RESULTS)
# ==============================================================================
# Look for CSVs generated by the Visualization Script
pathway_files <- list.files(viz_dir, pattern="\\.csv$", full.names=TRUE)

if(length(pathway_files) > 0) {
    cat("\nLOG: Found Pathway Results. Adding tabs...\n")
    for(f in pathway_files) {
        fname <- basename(f)
        
        # Skip if it's the master excel itself or session info
        if(grepl(".xlsx", fname) || grepl("session", fname)) next
        
        # Create readable tab name
        sheet_name <- make_tab_name(fname)
        cat(paste0("  > Adding Pathway Tab: ", sheet_name, " (from ", fname, ")\n"))
        
        # Read Data
        gsea_df <- read.csv(f, row.names=NULL)
        
        # Select/Order columns for clarity
        if("core_enrichment" %in% colnames(gsea_df)) {
             # Move core_enrichment to end because it's long
             gsea_df <- gsea_df %>% dplyr::select(ID, NES, p.adjust, everything(), core_enrichment)
        }
        
        # Add to Workbook (Check for duplicate tab names)
        if(!sheet_name %in% names(wb)) {
            addWorksheet(wb, sheet_name)
            writeData(wb, sheet_name, gsea_df)
        }
    }
} else {
    cat("WARNING: No pathway CSV files found in visualization directory.\n")
}

# ==============================================================================
# SAVE
# ==============================================================================
cat(paste0("\nLOG: Saving Master Excel to: ", outfile, "\n"))
saveWorkbook(wb, outfile, overwrite = TRUE)
cat("LOG: Done.\n")
